// <Auto-Generated/>

using System.Buffers;

namespace KeenConveyance.Util;

internal unsafe static class URIEncoder
{
    private static readonly IBaseAnyEncoder<char> s_encoding;

    static URIEncoder()
    {
        s_encoding = BaseAnyEncoding.CreateEncoder("abcdefghijklmnopqrstuvwxyz0123456789".AsSpan());
    }

    public static string EncodeAsString(in ReadOnlySpan<byte> data)
    {
        return s_encoding.EncodeToString(data);
    }
}
